<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseGameDump>true</UseGameDump>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.7" />
  </ItemGroup>
</Project>
