<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseGameDump>true</UseGameDump>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PrivateSekai.Server/PrivateSekai.Server.csproj" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>
</Project>
